spring:
  application:
    name: nonogram

  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:mem:nonogram;DB_CLOSE_DELAY=-1"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081